name = "boilerplate"
compatibility_date = "2024-12-19"
compatibility_flags = []
workers_dev = true
main = "server/src/index.ts"

assets = { directory = "./dist", binding = "ASSETS", not_found_handling = "single-page-application" }

[observability]
enabled = true

[build]
command = "bun run build"
watch_dir = [
  'client/src',
  'server/src',
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"
